import { Inter } from "next/font/google";
import "./globals.css";
import TopContact from "@/Components/Home route/TopContact";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
      <TopContact></TopContact>
       <div>
       {children}
       </div>
        </body>
    </html>
  );
}
